## R - lab 1 i 2

#### wersja R

In [14]:
R.version.string
getRversion()

[1] "R version 3.5.1 (2018-07-02)"

[1] '3.5.1'

#### pomoc

In [17]:
#help(help)
?help
#?"+"
#library(help = "stats")

#### działania

In [114]:
2 + 2
3 - 2
2 * 7
9 / 4
2 ^ 5

10 %% 3
10 %/% 3

2 == 2
2 != 2
3 > 2
3 >= 2
3 < 2
3 <= 2

TRUE | FALSE
(2 > 3) | (4 > 2)
TRUE & FALSE
(2 > 3) & (4 > 2)
!TRUE == FALSE
!!FALSE == !TRUE

[1] 4

[1] 1

[1] 14

[1] 2.25

[1] 32

[1] 1

[1] 3

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] TRUE

#### Inf i NaN

In [1]:
1/0
0/0

[1] Inf

[1] NaN

#### print vs cat

In [32]:
print("My name is Inigo Montoya. You killed my father. Prepare to die.")
print(1)
cat("My name is Inigo Montoya. You killed my father. Prepare to die.")
cat(1)
cat("\nMy name is Inigo Montoya.", "You killed my father.", "Prepare to d
ie.")

[1] "My name is Inigo Montoya. You killed my father. Prepare to die."
[1] 1
My name is Inigo Montoya. You killed my father. Prepare to die.1
My name is Inigo Montoya. You killed my father. Prepare to d
ie.

#### paste

In [59]:
text <- paste(l1, l2, l3, l4, sep = "\n")
cat(text)

Nie bądź bezpieczny
poeta pamięta
Możesz go zabić - narodzi się nowy
Spisane będą czyny i rozmowyNie bądź bezpieczny poeta pamięta Możesz go zabić - narodzi się nowy Spisane będą czyny i rozmowy

#### katalog roboczy

In [34]:
?getwd
getwd()
#setwd(dir)

[1] "C:/Users/adrianna.tokarska"

In [37]:
#no multiline comments

#### zmienne i przypisania

In [44]:
l1 <- "Nie bądź bezpieczny" # zmienna l1
l2 = "poeta pamięta" # zmienna l2 (wariant z operatorem "=" jest niezalecany)
"Możesz go zabić - narodzi się nowy" -> l3 # przypisanie z "lewej na prawo"!
assign("l4", "Spisane będą czyny i rozmowy") # uwaga na "" w definicji zmiennej "l4"

.x2 <- 3.5 #zmienna niewidoczna w Environment

print(l1)
print(l2)
print(l3)
print(l4)
print(.x2)

[1] "Nie bądź bezpieczny"
[1] "poeta pamięta"
[1] "Możesz go zabić - narodzi się nowy"
[1] "Spisane będą czyny i rozmowy"
[1] 3.5


#### tworzenie wektorów - c()

In [95]:
c(TRUE, FALSE) == c(FALSE, FALSE)
c(TRUE, FALSE) && c(TRUE, FALSE)
c(FALSE, TRUE) | c(TRUE, FALSE)
c(FALSE, TRUE) || c(TRUE, FALSE)

[1] FALSE  TRUE

[1] TRUE

[1] TRUE TRUE

[1] TRUE

In [70]:
class(TRUE)
class(FALSE + 1)
class(FALSE + 2L)
class(TRUE + FALSE)

[1] "logical"

[1] "numeric"

[1] "integer"

[1] "integer"

In [90]:
(to.be <- FALSE == FALSE) | !to.be

[1] TRUE

#### listowanie i usuwanie zmiennych

In [93]:
ls()

character(0)

In [92]:
rm(list = ls())
ls()

character(0)

#### wektory
The atomic modes are "logical", "integer", "numeric" (synonym "double"), "complex", "character" and "raw". 

In [3]:
5:1
1:5
class(1:5)
is.vector(1:5)
10 %in% -5:5

[1] 5 4 3 2 1

[1] 1 2 3 4 5

[1] "integer"

[1] TRUE

[1] FALSE

In [17]:
v1 <- 1:5
v2 <- c(10,20,30,40,50)
v3 <- seq(100, 500, by = 100)

is.atomic(v1)
v4 <- c(TRUE, 1L, 2.5, "abc")
class(v4)
v5 <- c(TRUE, 1L, 2.5)
class(v5)

[1] TRUE

[1] "character"

[1] "numeric"

In [20]:
v6 <- 1:10
v7 <- c(1,0)
v6 * v7

[1] 1 0 3 0 5 0 7 0 9 0

#### macierze

In [34]:
M = matrix( c(1,2,3,4,5,6), nrow = 2, ncol = 3, byrow = TRUE)
class(M)
M
t(M) #macierz transponowana
M %*% t(M)

[1] "matrix"

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2]
[1,] 14   32  
[2,] 32   77

In [40]:
M1 <- matrix(c(1:12), nrow = 3)
M1
class(M1)
is.vector(M1)
dim(M1)
nrow(M1)
ncol(M1)


[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[1] "matrix"

[1] FALSE

[1] 3 4

[1] 3

[1] 4

In [47]:
M2 <- matrix(c(1:12), nrow = 3, byrow = TRUE)
dimnames(M2) <- list(rownames, colnames)
M2

c1 c2 c3 c4
r1 1   2  3  4
r2 5   6  7  8
r3 9  10 11 12

In [48]:
rownames <- c("r1", "r2", "r3")
colnames = c("c1", "c2", "c3", "c4")
M3 <- matrix(c(1:12), nrow = 3, byrow = TRUE, dimnames = list(rownames, colnames))
M3

c1 c2 c3 c4
r1 1   2  3  4
r2 5   6  7  8
r3 9  10 11 12

In [52]:
M2[1,2]
M2["r1","c2"]
M2
M2[1,]
M2[c(1,3),]
M2
M2[c(1,3), c(2,4)]

[1] 2

[1] 2

c1 c2 c3 c4
r1 1   2  3  4
r2 5   6  7  8
r3 9  10 11 12

c1 c2 c3 c4 
 1  2  3  4

c1 c2 c3 c4
r1 1   2  3  4
r3 9  10 11 12

c1 c2 c3 c4
r1 1   2  3  4
r2 5   6  7  8
r3 9  10 11 12

c2 c4
r1  2  4
r3 10 12

In [54]:
M1[1,2] <- 12
M1
M2["r2","c2"] <- 22
M2
M1[c(1,2), c(1,2)] = matrix(rep(0,4))
M1

[,1] [,2] [,3] [,4]
[1,] 0    12   7    10  
[2,] 0     0   8    11  
[3,] 3     6   9    12

c1 c2 c3 c4
r1 1   2  3  4
r2 5  22  7  8
r3 9  10 11 12

[,1] [,2] [,3] [,4]
[1,] 0    0    7    10  
[2,] 0    0    8    11  
[3,] 3    6    9    12

In [56]:
M1 <- matrix(c(1:12), nrow = 3)
M1 - 1
M1^2
M1 * (M1 - 1)
M1 ^ (M1 - 7)
(M1 - 1) / M1

[,1] [,2] [,3] [,4]
[1,] 0    3    6     9  
[2,] 1    4    7    10  
[3,] 2    5    8    11

[,1] [,2] [,3] [,4]
[1,] 1    16   49   100 
[2,] 4    25   64   121 
[3,] 9    36   81   144

[,1] [,2] [,3] [,4]
[1,] 0    12   42    90 
[2,] 2    20   56   110 
[3,] 6    30   72   132

[,1]       [,2]      [,3] [,4]  
[1,] 1.00000000 0.0156250  1     1000
[2,] 0.03125000 0.0400000  8    14641
[3,] 0.01234568 0.1666667 81   248832

[,1]      [,2]      [,3]      [,4]     
[1,] 0.0000000 0.7500000 0.8571429 0.9000000
[2,] 0.5000000 0.8000000 0.8750000 0.9090909
[3,] 0.6666667 0.8333333 0.8888889 0.9166667

In [58]:
M1 <- matrix(c(1:12), nrow = 3)
M1
cbind(M1, c(13,14,15))
#?cbind
M1
M1 <- cbind(M1, c(13,14,15))
M1
ncol(M1)
rbind(M1, rep(100, ncol(M1)))

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

[1] 5

[,1] [,2] [,3] [,4] [,5]
[1,]   1    4    7   10   13 
[2,]   2    5    8   11   14 
[3,]   3    6    9   12   15 
[4,] 100  100  100  100  100

#### NA , NaN , Inf i NULL

In [33]:
#?NA
#?NaN
#?Inf
#?NULL

#### tablica

An array in R can have one, two or more dimensions. It is simply a vector which is stored with additional attributes giving the dimensions (attribute "dim") and optionally names for those dimensions (attribute "dimnames"). 

A two-dimensional array is the same thing as a matrix. 

In [60]:
#?array
A1 <- array(c(1:9, 101:109, 1001:1009), dim = c(3,3,3))
A1
A1[1,2,3]
dimnames(A1) = list(c("a1", "a2", "a3"), c("b1", "b2", "b3"), c("c1", "c2", "c3"))
A1

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]  101  104  107
[2,]  102  105  108
[3,]  103  106  109

, , 3

     [,1] [,2] [,3]
[1,] 1001 1004 1007
[2,] 1002 1005 1008
[3,] 1003 1006 1009

[1] 1004

, , c1

   b1 b2 b3
a1  1  4  7
a2  2  5  8
a3  3  6  9

, , c2

    b1  b2  b3
a1 101 104 107
a2 102 105 108
a3 103 106 109

, , c3

     b1   b2   b3
a1 1001 1004 1007
a2 1002 1005 1008
a3 1003 1006 1009

#### czynnik - factor

In [61]:
gen <- c("male","male","female","female","male","female","male")
class(gen)
is.factor(gen)



[1] "character"

[1] FALSE

#### SQL - library(sqldf)


In [24]:
library(sqldf)

data(titanic3, package="PASWR")
colnames(titanic3)
head(titanic3)

sqldf('select age, count(*) from titanic3 where age is not null group by age')

ERROR: Error in library(sqldf): there is no package called 'sqldf'
